on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  ubuntu:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: 12.x

    - name: Install packages
      run: yarn --frozen-lockfile

    - name: Linting
      run: yarn lint

    - name: Test node
      run: yarn test

    - name: Test Chrome
      run: yarn test:chrome

    - name: Test Firefox
      run: yarn test:firefox
  macos:
    runs-on: macos-10.15
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: 12.x

    - name: Install packages
      run: yarn --frozen-lockfile

    - name: Test Safari
      run: yarn test:safari
